const TYPE = {
    GET_ALL_DOGS : 'GET_ALL_DOGS',
    GET_ALL_TEMPERAMENTS: 'GET_ALL_TEMPERAMENTS',
    GET_ALL_WEIGHT : 'GET_ALL_WEIGHT', 
    FILTER_BY_TEMPERAMENT: 'FILTER_BY_TEMPERAMENT',
    FILTER_BY_WEIGHT: 'FILTER_BY_WEIGHT',
    ORDER_BY_NAME: 'ORDER_BY_NAME',
    ORDER_ORIGEN_CREATE: 'ORDER_ORIGEN_CREATE',
    FILTER_ALL_DOGS: 'TYPE.FILTER_ALL_DOGS',
    SEARCH: 'SEARCH',
    SEARC_ID :  'SEARC_ID',
    CLOSED_ERROR :  'CLOSED_ERROR',
    DUPLICATE_BREED: 'DUPLICATE_BREED',
}



export default TYPE